<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LightLaunchpad.Core\LightLaunchpad.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\LightLaunchpad.App\Assets\LightLaunchpad.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\LightLaunchpad.App\Assets\LightLaunchpad.ico" Link="Assets\LightLaunchpad.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
